### ISSUE TITLE
Color scheme is not as your prevew

### ISSUE THREAD

**Issue by edtsz** [zaynali53/DotENV#13]
I'm using:
SublimeText 3 (version 3.2.2, build 3211)
ColorScheme: Monokai

![image](https://user-images.githubusercontent.com/3809579/86020905-e4391780-b9fe-11ea-91fc-fd3cffe2e1b4.png)

**Comment by zaynali53** [comment]
Hello @edtsz Thanks for asking. 😊

Preview was just a comparison between Bash language (used to colorize .env files) and DotENV package.

Monokai doesn't color specific syntax definition so for that reason you need to check other available options.

In my case I use one my own color scheme. [Acme Color Scheme](https://github.com/zaynali53/acme-color-scheme)

![image](https://user-images.githubusercontent.com/8646770/86118672-9a2d6000-baea-11ea-88da-8b17529b446c.png)
