### ISSUE TITLE
Support for .env.default and env.defaults file extension

### ISSUE THREAD

**Issue by cobbles** [zaynali53/DotENV#14]
Would it be possible to add support for `.env.default` and `.env.defaults` file names?

My current use case is we use a default file for base configuration and then environment specific config with a regular `.env` file

I know I could use `.env-sample` (.env.example) is already in use in our project but it does not really convey the same meaning

Happy to submit the changes required if you would like them included :)

**Comment by zaynali53** [comment]
Hello @cobbles 

Sorry for the late reply as I was on a vacation.

I've added the support for `.env.default` and `.env.defaults` file types. https://github.com/zaynali53/DotENV/commit/2a62e68b57a8352a7d451dcef965613f6bac39fc

Thank You! 🙂

**Comment by cobbles** [comment]
@zaynali53 Legend! thanks for that :smile:
