### ISSUE TITLE
Can't enter custom names

### ISSUE THREAD

**Issue by Esqarrouth** [zaynali53/DotENV#15]
I have many environment files for different instances of my server. I want to give them custom names, for example:
- .env.servername
- .env.servername.static
- .env.servername.api
- .env.servername.socket

I check the extension settings and couldn't find anything:

<img width="1422" alt="Screen Shot 2021-03-13 at 19 10 28" src="https://user-images.githubusercontent.com/5816878/111036329-c6e29700-842f-11eb-94d4-755fc67bbfc8.png">

- There is no setting to add custom file extensions
- There is no setting to toggle on .env.*

Any tips, suggestions? Alternative extensions?

**Comment by Narretz** [comment]
I have a custom .env.something file **and set the syntax manually,** and the highlighting in Sublime Text 3 works

**Comment by Esqarrouth** [comment]
> I have a custom .env.something file **and set the syntax manually,** and the highlighting in Sublime Text 3 works

how do you set the syntax manually?

**Comment by Narretz** [comment]
Use the command palette, Set Syntax ... should show an entry for dotenv

**Comment by Narretz** [comment]
Just noticed the ApplySyntax package could help with applying the syntax to arbitrary files: https://packagecontrol.io/packages/ApplySyntax

**Comment by Esqarrouth** [comment]
> Use the command palette, Set Syntax ... should show an entry for dotenv

<img width="1157" alt="Screen Shot 2021-09-10 at 16 14 34" src="https://user-images.githubusercontent.com/5816878/132858789-0b0c3f10-8fe4-45d2-bcbc-d52f0800f04e.png">

Were you talking about Sublime for that? Because `Set Syntax` came up empty for VSC

**Comment by Narretz** [comment]
I'm sorry I didn't realize you use VsCode. However, I wrote about Sublime Code in my original comment.

**Comment by kurucaner** [comment]
I just added the following to the settings.json and it work for any .env files now!

`"files.associations": {
    "*.env*": "dotenv"
  }`

**Comment by Esqarrouth** [comment]
@kurucaner thanks

is this change pushed to the repo and automatically released, or do I need to edit something somewhere?

**Comment by kurucaner** [comment]
@goktugyil you need to add it to the settings.json file in vscode manually. It's not pushed to the repo.

**Comment by Esqarrouth** [comment]
Perfect, it works, thanks!
