### ISSUE TITLE
Support .env.prod files

### ISSUE THREAD

**Issue by GraysonFreking** [zaynali53/DotENV#7]
.env.prod files are commonplace in Ionic -- could the plugin be updated to support this?

**Comment by zaynali53** [comment]
@GraysonFreking Thanks! I've added support for .env.prod extension also for .env.dev. 😄

**Comment by zaynali53** [comment]
@GraysonFreking Thanks! I've added support for `.env.prod` extension, also for `.env.dev` too. 😄
