### ISSUE TITLE
support .flaskenv files

### ISSUE THREAD

**Issue by diniremix** [zaynali53/DotENV#8]
The **.flaskenv** files for projects with [Flask](http://flask.pocoo.org/) Could the add-in be updated to support this?
![Imgur](https://i.imgur.com/SetAgxj.png)

Thanks!

**Comment by zaynali53** [comment]
@diniremix Thanks! 😄 I've added support for `.flaskenv`.

However, Your editor in this image is VS Code. Which means DotENV package for it, is just a port of this repository by **mikestead**. So he also have to update his extension in order to get these changes.

Cheers!

**Comment by diniremix** [comment]
Yes, thank you very much, I already reported it in [mikestead/vscode-dotenv](https://github.com/mikestead/vscode-dotenv/issues/13).

please, close this issue.
